spring.application.name=AirBnB

spring.datasource.url=jdbc:mysql://localhost:3306/airbnb
spring.datasource.username=root
spring.datasource.password=12378900nb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql= true

jwt.secretKey=jasieufajksnfdiasbudfajesiubfaibfdiasbdfbasidfasdfhiasbdfiasbdifweniwbfiobsdnbfasbdfjskbjfaeeeasiudbfiasbdfiaubdsfsadfasdfasdfasfwceneeayrajfoiai

server.servlet.context-path=/api/v1